### ISSUE TITLE
Using project through composer

### ISSUE THREAD

**Issue by r-englund** [dadeg/php-crowdflower#14]
Hi, 
FVI, I just tried to include this project within a project of my by following the README.md. The readme tells me to use 

``` json
 "dadeg/php-crowdflower": "0.1.*"
```

to enable it, but that did not work, changing to  

``` json
"dadeg/php-crowdflower": "dev-master"
```

solved the problem.

**Comment by dadeg** [comment]
Thanks, I made the release so it should work now.
